<?php  
 
ob_start(); 
 
$API_KEY = 'zC71UM4AJv5Mk4ESZx4XYbE56oLQvUoMVFJkVv_vZoY';  
define('API_KEY',$API_KEY); 
function bot($method,$datas=[]){ 
    $url = "https://api.telegram.org/bot".API_KEY."/".$method; 
    $ch = curl_init(); 
    curl_setopt($ch,CURLOPT_URL,$url); 
    curl_setopt($ch,CURLOPT_RETURNTRANSFER,true); 
    curl_setopt($ch,CURLOPT_POSTFIELDS,$datas); 
    $res = curl_exec($ch); 
    if(curl_error($ch)){ 
        var_dump(curl_error($ch)); 
    }else{ 
        return json_decode($res); 
    } 
} 
$update = json_decode(file_get_contents('php://input')); 
$message = $update->message; 
$from_id = $message->from->id; 
$chat_id = $message->chat->id; 
$txt = $message->text;
$from_id = $message->from->id;
 
if($txt != "Ø­Ø¬Ø±Ø©" && $txt != "ÙˆØ±Ù‚Ø©" && $txt != "Ù…Ù‚Øµ" && $txt == "/start"){
bot('sendMessage',[
'chat_id'=>$chat_id,
'text'=>"ØªØ±Ø­ÙŠØ¨",
'parse_mode'=>"markdown", 
]); 
}
$random = array('Ø§Ù†Øª ÙØ²Øª Ù„Ø§Ù† Ø§Ø®ØªÙŠØ§Ø±ÙŠ Ù…Ù‚Øµ ğŸŒğŸ¤ğŸ»', 'Ø§Ù†Ø§ ÙØ²Øª Ù„Ø§Ù† Ø§Ø®ØªÙŠØ§Ø±ÙŠ ÙˆØ±Ù‚Ø© ğŸŒğŸ–±', 'Ù†Ø­Ù† Ù…ØªØ¹Ø§Ø¯Ù„ÙŠÙ† ğŸŒâœŠğŸ»');
$random1 = array_rand($random, 1);
$rrues = array('Ø§Ù†Øª Ø§Ù„ÙØ§Ø¦Ø² Ù„Ø§Ù† Ø§Ø®ØªÙŠØ§Ø±ÙŠ Ø­Ø¬Ø±Ø© ğŸŒâœŠğŸ»', 'Ù†Ø­Ù† Ù…ØªØ¹Ø§Ø¯Ù„ÙŠÙ† ğŸ¤ğŸŒ', 'Ø§Ù†Ø§ ÙØ²Øª Ù„Ø§Ù† Ø§Ø®ØªÙŠØ§Ø±ÙŠ Ù…Ù‚Øµ ğŸŒğŸ¤ğŸ»');
$rues = array_rand($rrues);
$ccut = array('Ù†Ø­Ù† Ù…ØªØ¹Ø§Ø¯Ù„ÙŠÙ† ğŸŒğŸ¤ ','Ø§Ù†Ø§ ÙØ²Øª Ù„Ø§Ù† Ø§Ø®ØªÙŠØ§Ø±ÙŠ Ø­Ø¬Ø±Ø© ğŸŒâœŠğŸ»', ' Ø§Ù†Øª ÙØ²Øª Ù„Ø§Ù† Ø§Ø®ØªÙŠØ§Ø±ÙŠ ÙˆØ±Ù‚Ø© ğŸ–±ğŸŒ');
$cut = array_rand($ccut);

if($txt == "Ø­Ø¬Ø±Ø©"){
bot('sendMessage',[
'chat_id'=>$chat_id,
'text'=>$random[$random1],
'reply_to_message_id'=>$message->message_id, 
]);
}
if($txt == "Ù…Ù‚Øµ"){
bot('sendMessage',[
'chat_id'=>$chat_id,
'text'=>$ccut[$cut],
'reply_to_message_id'=>$message->message_id, 
]);
}
if($txt == "ÙˆØ±Ù‚Ø©"){
bot('sendMessage',[
'chat_id'=>$chat_id,
'text'=>$rrues[$rues],
'reply_to_message_id'=>$message->message_id, 
]);
}
